config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals

  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :comment, :commentable_id, :commentable_type, :commenter_id, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :commenter, class_name: "User", foreign_key: :commenter_id

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, :description, :user, presence: true
  validates :private, :completed, inclusion: { in: [true, false]}

  belongs_to :user
  has_many :comments, as: :commentable

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :goals
  has_many :comments, as: :commentable
  has_many :user_comments, class_name: 'Comment', foreign_key: :commenter_id

  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user
    @user.is_password?(password) ? @user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token
  end

  def logout!
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def redirect_on_login
    if logged_in?
      redirect_to(user_url(current_user))
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    unless @comment.save
      flash[:errors] = @comment.errors.full_messages
    end
    redirect_to "/#{@comment.commentable_type.downcase.pluralize}/#{@comment.commentable_id}"
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    redirect_to "/#{@comment.commentable_type.downcase.pluralize}/#{@comment.commentable_id}"
  end

  def comment_params
    params.require(:comment).permit(:comment, :commentable_id, :commentable_type, :commenter_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @goal = Goal.new
    render :new
  end

  def create

    @goal = Goal.new(goal_params)
    if @goal.save!
      redirect_to user_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    render :show
  end

  def edit

    render :edit
  end

  def update
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def destroy
    @goal = Goal.find(params[:id]).destroy
    redirect_to user_url(@goal.user_id)
  end

  def goal_params
    params.require(:goal).permit(:name, :description, :private, :user_id, :completed)
  end

  def ensure_correct_user
    @goal = Goal.find(params[:id])
    unless current_user.id == @goal.user_id
      flash[:errors] = ["Invalid User- Cannot change others goals you monster"]
      redirect_to user_url(current_user)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_on_login, except: [:destroy]

  def new
  end

  def create
    @user = User.find_by_credentials( params[:user][:username],
                                      params[:user][:password])
    if @user.nil?
      render :new
    else
      login!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout!
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden"
          name="authenticity_token"
          value="#{form_authenticity_token}"
          >
    HTML
  end

  def public_goals(user)
    user.goals.where(private: false)
  end

  def private_goals(user)
    user.goals.where(private:true)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <label>Comment
    <input type="textarea" name="comment[comment]"></textarea>
  </label>

  <input type="hidden" name="comment[commentable_id]" value="<%= commentable.id %>">
  <input type="hidden" name="comment[commentable_type]" value="<%= commentable.model_name %>">
  <input type="hidden" name="comment[commenter_id]" value="<%= current_user.id %>">

  <input type="submit" value="Add Comment">
</form>

app/views/comments/_show.html.erb
<% comments.each do |comment| %>
  <p><%= comment.comment %></p>
  <h5>Posted by <%= comment.commenter.username %></h5>
  <% if comment.commenter == current_user || comment.commentable_id == current_user.id %>
    <form action="<%= comment_url(comment.id) %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <%= auth_token %>
      <input type="submit" value="Delete Comment" >
    </form>
  <% end %>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Goal for <%= current_user.username %></h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>Title
    <input type="string" name="goal[name]" value="<%= @goal.name %>">
  </label>

  <label>Description
    <input type="string" name="goal[description]" value="<%= @goal.description %>">
  </label>


  <label>Public
    <input type="radio" name="goal[private]" value="false" <%= @goal.private ? "" : "checked" %>>
  </label>

  <label>Private
    <input type="radio" name="goal[private]" value="true" <%= @goal.private ? "checked" : "" %>>
  </label>


  <input type="submit" value="Update Goal" >
</form>

app/views/goals/new.html.erb
<h1>Add Goal to <%= current_user.username %></h1>

<form action="<%= goals_url %>" method="post">
  <%= auth_token %>
  <label>Title
    <input type="string" name="goal[name]" value="<%= @goal.name %>">
  </label>

  <label>Description
    <input type="string" name="goal[body]" value="<%= @goal.description %>">
  </label>

  <label>Public
    <input type="radio" name="goal[private]", value="false">
  </label>

  <label>Private
    <input type="radio" name="goal[private]", value="true">
  </label>

  <input type="submit" value="Submit Goal" >
</form>

app/views/goals/show.html.erb
<h1> <%= @goal.name %> </h1>

<% if @goal.completed %>
  <h2> Goal is Completed!</h2>
<% end %>

<h3>Goal Description: <%= @goal.description %> </h3>
<h3>Goal Publicity: <%= @goal.private ? "Private" : "Public" %> </h3>
<h3>


<% if current_user.id == @goal.user_id %>
<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>Complete
    <input type="radio" name="goal[completed]" value="true" <%= @goal.completed ? "checked" : "" %>>
  </label>
  <label>Incomplete
      <input type="radio" name="goal[completed]" value="false" <%= @goal.completed ? "" : "checked" %>>
  </label>


  <input type="submit" value="Update Goal" >
</form>
<% end %>

<h3>Comments</h3>
<%= render 'comments/show', { comments: @goal.comments } %>
<h4>Add Comment</h4>
<%= render 'comments/new', { commentable: @goal } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= yield %>

<% if logged_in? %>
  <h4>Signed in as: <%= current_user.username %></h4>
  <form action="<%= session_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= auth_token %>
    <input type="submit" value="Sign Out" >
  </form>
<% else %>
  <a href="<%= new_session_url %>">Sign In</a>
  <a href="<%= new_user_url %>">Sign Up</a>
<% end %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Username
    <input type="string" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="string" name="user[password]" value="<%= @user.password %>">
  </label>

  <input type="submit" value="Sign Up" >
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h3>Your Goals</h3>
<ul>
  <% public_goals(@user).each do |goal| %>
    <li><a href="<%= goal_url(goal) %>"><%= goal.name %></a>
      <% if current_user == @user %>
        <a href="<%= edit_goal_url(goal) %>">Edit Goal</a>
        <form action="<%= goal_url(goal) %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <input type="submit" value="Delete Goal" >
        </form>
      <% end %>

    </li>
  <% end %>
</ul>
<% if current_user == @user %>
  <h3>Private Goals</h3>
  <ul>
  <% private_goals(@user).each do |goal| %>
    <li><a href="<%= goal_url(goal) %>"><%= goal.name %></a>
        <a href="<%= edit_goal_url(goal) %>">Edit Goal</a>
        <form action="<%= goal_url(goal) %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <input type="submit" value="Delete Goal" >
        </form>
    </li>

    <% end %>
  </ul>
<% end %>
<a href="<%= new_goal_url %>">Add Goal</a>

<h3>Comments</h3>
<%= render 'comments/show', comments: @user.comments %>
<h4>Add Comment</h4>
<%= render 'comments/new', commentable: @user %>